# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1167, 491)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Main_Button_LineTextChange = QtWidgets.QPushButton(self.centralwidget)
        self.Main_Button_LineTextChange.setGeometry(QtCore.QRect(180, 30, 93, 28))
        self.Main_Button_LineTextChange.setObjectName("Main_Button_LineTextChange")
        self.Main_Label_Label01 = QtWidgets.QLabel(self.centralwidget)
        self.Main_Label_Label01.setGeometry(QtCore.QRect(50, 70, 191, 31))
        self.Main_Label_Label01.setObjectName("Main_Label_Label01")
        self.Main_LineText_LineText01 = QtWidgets.QLineEdit(self.centralwidget)
        self.Main_LineText_LineText01.setGeometry(QtCore.QRect(50, 30, 113, 21))
        self.Main_LineText_LineText01.setObjectName("Main_LineText_LineText01")
        self.Main_ComboBox_RegionList = QtWidgets.QComboBox(self.centralwidget)
        self.Main_ComboBox_RegionList.setGeometry(QtCore.QRect(80, 150, 81, 22))
        self.Main_ComboBox_RegionList.setObjectName("Main_ComboBox_RegionList")
        self.Main_Button_GraphShow = QtWidgets.QPushButton(self.centralwidget)
        self.Main_Button_GraphShow.setGeometry(QtCore.QRect(180, 150, 91, 23))
        self.Main_Button_GraphShow.setObjectName("Main_Button_GraphShow")
        self.Main_Label_year = QtWidgets.QLabel(self.centralwidget)
        self.Main_Label_year.setGeometry(QtCore.QRect(570, 30, 101, 21))
        self.Main_Label_year.setObjectName("Main_Label_year")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(570, 70, 451, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.Main_VerticalLayout_ShowGraph = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.Main_VerticalLayout_ShowGraph.setContentsMargins(0, 0, 0, 0)
        self.Main_VerticalLayout_ShowGraph.setObjectName("Main_VerticalLayout_ShowGraph")
        self.Main_ListWidget_RegionSelect = QtWidgets.QListWidget(self.centralwidget)
        self.Main_ListWidget_RegionSelect.setGeometry(QtCore.QRect(455, 70, 111, 321))
        self.Main_ListWidget_RegionSelect.setObjectName("Main_ListWidget_RegionSelect")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1167, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Main_Button_LineTextChange.setText(_translate("MainWindow", "변경"))
        self.Main_Label_Label01.setText(_translate("MainWindow", "TextLabel"))
        self.Main_Button_GraphShow.setText(_translate("MainWindow", "그래프 보기"))
        self.Main_Label_year.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
